data: packages.csv
#data: |
#  package
#  agamigo.io/vecty-material/demos/button

#github.com/dave/play
rate: 1
workers: 5
worker-type: "jsgo"
timeout: 300000
payload-template:
  path: "{{ .package }}"
